# Generated by Django 3.2.3 on 2021-06-07 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing22'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing22',
        ),
    ]
