# Generated by Django 3.2.3 on 2021-07-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='PostDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
