# Generated by Django 3.2.3 on 2021-07-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_listing_postdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='PostDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
