# Generated by Django 3.2.3 on 2021-07-01 22:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_listing_postdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='PostTime',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='PostDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
