# Generated by Django 3.2.3 on 2021-07-05 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_user_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Category',
            field=models.ForeignKey(default='No Category', on_delete=django.db.models.deletion.CASCADE, to='auctions.categories'),
        ),
    ]
