# Generated by Django 3.2.3 on 2021-07-08 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20210704_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='CurrentBid',
            new_name='currentBid',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='HighestBidder',
            new_name='highestBidder',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='Listing',
            new_name='listing',
        ),
    ]
