# Generated by Django 3.2.3 on 2021-07-08 03:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20210707_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='highestBidder',
            new_name='Bidder',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='numberOfBids',
        ),
        migrations.AddField(
            model_name='bid',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='Bids',
            field=models.ManyToManyField(blank=True, to='auctions.Bid'),
        ),
    ]
