# Generated by Django 3.2.3 on 2021-07-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20210707_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Price',
            field=models.DecimalField(decimal_places=2, help_text='Price in Canadian dollars', max_digits=100),
        ),
    ]
