# Generated by Django 3.2.3 on 2021-07-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_listing_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
